version: '3.6'
services:
  nginx:
    container_name: nginx
    image: nginx:1.18.0
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./project:/home/project
    ports:
      - 80:80
      - 443:443
    networks:
      - default-network
    restart: always
networks:
  default-network:
    driver: bridge
